ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.products REPLICA IDENTITY FULL;
ALTER TABLE public.gate_passes REPLICA IDENTITY FULL;
ALTER TABLE public.product_timeline REPLICA IDENTITY FULL;
ALTER TABLE public.gate_pass_timeline REPLICA IDENTITY FULL;